// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_login from "./routes/api/login.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $managment_layout from "./routes/managment/_layout.tsx";
import * as $managment_middleware from "./routes/managment/_middleware.ts";
import * as $managment_dependent_id_ from "./routes/managment/dependent/[id].tsx";
import * as $managment_dependent_all from "./routes/managment/dependent/all.tsx";
import * as $managment_dependent_register from "./routes/managment/dependent/register.tsx";
import * as $managment_dependent_show from "./routes/managment/dependent/show.tsx";
import * as $managment_index from "./routes/managment/index.tsx";
import * as $managment_product_id_ from "./routes/managment/product/[id].tsx";
import * as $managment_product_middleware from "./routes/managment/product/_middleware.ts";
import * as $managment_product_delete_id_ from "./routes/managment/product/delete/[id].ts";
import * as $managment_product_register from "./routes/managment/product/register.tsx";
import * as $managment_product_show from "./routes/managment/product/show.tsx";
import * as $managment_product_update_id_ from "./routes/managment/product/update/[id].tsx";
import * as $managment_supplier_id_ from "./routes/managment/supplier/[id].tsx";
import * as $managment_supplier_middleware from "./routes/managment/supplier/_middleware.ts";
import * as $managment_supplier_delete_id_ from "./routes/managment/supplier/delete/[id].ts";
import * as $managment_supplier_register from "./routes/managment/supplier/register.tsx";
import * as $managment_supplier_show from "./routes/managment/supplier/show.tsx";
import * as $managment_supplier_update_id_ from "./routes/managment/supplier/update/[id].tsx";
import * as $managment_user_id_ from "./routes/managment/user/[id].tsx";
import * as $managment_user_delete_id_ from "./routes/managment/user/delete/[id].ts";
import * as $managment_user_show from "./routes/managment/user/show.tsx";
import * as $managment_user_update_id_ from "./routes/managment/user/update/[id].tsx";
import * as $register from "./routes/register.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/login.ts": $api_login,
    "./routes/api/logout.ts": $api_logout,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/managment/_layout.tsx": $managment_layout,
    "./routes/managment/_middleware.ts": $managment_middleware,
    "./routes/managment/dependent/[id].tsx": $managment_dependent_id_,
    "./routes/managment/dependent/all.tsx": $managment_dependent_all,
    "./routes/managment/dependent/register.tsx": $managment_dependent_register,
    "./routes/managment/dependent/show.tsx": $managment_dependent_show,
    "./routes/managment/index.tsx": $managment_index,
    "./routes/managment/product/[id].tsx": $managment_product_id_,
    "./routes/managment/product/_middleware.ts": $managment_product_middleware,
    "./routes/managment/product/delete/[id].ts": $managment_product_delete_id_,
    "./routes/managment/product/register.tsx": $managment_product_register,
    "./routes/managment/product/show.tsx": $managment_product_show,
    "./routes/managment/product/update/[id].tsx": $managment_product_update_id_,
    "./routes/managment/supplier/[id].tsx": $managment_supplier_id_,
    "./routes/managment/supplier/_middleware.ts":
      $managment_supplier_middleware,
    "./routes/managment/supplier/delete/[id].ts":
      $managment_supplier_delete_id_,
    "./routes/managment/supplier/register.tsx": $managment_supplier_register,
    "./routes/managment/supplier/show.tsx": $managment_supplier_show,
    "./routes/managment/supplier/update/[id].tsx":
      $managment_supplier_update_id_,
    "./routes/managment/user/[id].tsx": $managment_user_id_,
    "./routes/managment/user/delete/[id].ts": $managment_user_delete_id_,
    "./routes/managment/user/show.tsx": $managment_user_show,
    "./routes/managment/user/update/[id].tsx": $managment_user_update_id_,
    "./routes/register.tsx": $register,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
